### ISSUE TITLE
What is each value?

### ISSUE THREAD

**Issue by ghost** [isohuntto/openbay-db-dump#4]
Alright so I downloaded this and want to create something but I'm stuck at what each part is.

The first part is the torrent name, what are values 2,3 and 4 for and then the fifth value is the category. The last 2 are seeders/leechers?

Sorry for not being able to fully explain.

**Comment by LucasRoot** [comment]
This problem has already been resolved
https://github.com/isohuntto/openbay-db-dump/issues/1
